export const SKILLS = [
  "Listening",
  "Speaking",
  "Leadership",
  "Teamwork",
  "Creativity",
  "Adapting",
  "Planning & Problem-Solving",
] as const;

export type SkillName = (typeof SKILLS)[number];

export const SUB_SCORES: Record<SkillName, string[]> = {
  Listening: [
    "Active Listening",
    "Comprehension",
    "Empathy",
    "Note-Taking",
    "Following Directions",
    "Clarifying Questions",
    "Nonverbal Awareness",
    "Patience",
    "Retention",
    "Critical Listening",
  ],
  Speaking: [
    "Clarity",
    "Confidence",
    "Vocabulary",
    "Persuasion",
    "Tone Control",
    "Audience Awareness",
    "Conciseness",
    "Storytelling",
    "Public Speaking",
    "Articulation",
  ],
  Leadership: [
    "Decision Making",
    "Delegation",
    "Motivation",
    "Vision Setting",
    "Accountability",
    "Conflict Resolution",
    "Mentoring",
    "Strategic Thinking",
    "Integrity",
    "Resilience",
  ],
  Teamwork: [
    "Collaboration",
    "Reliability",
    "Flexibility",
    "Communication",
    "Supportiveness",
    "Shared Responsibility",
    "Trust Building",
    "Conflict Management",
    "Active Participation",
    "Consensus Building",
  ],
  Creativity: [
    "Originality",
    "Brainstorming",
    "Risk Taking",
    "Resourcefulness",
    "Curiosity",
    "Imagination",
    "Innovation",
    "Experimentation",
    "Aesthetic Sense",
    "Lateral Thinking",
  ],
  Adapting: [
    "Flexibility",
    "Stress Management",
    "Open-Mindedness",
    "Learning Agility",
    "Emotional Regulation",
    "Cultural Sensitivity",
    "Recovery Speed",
    "Situational Awareness",
    "Growth Mindset",
    "Tolerance for Ambiguity",
  ],
  "Planning & Problem-Solving": [
    "Goal Setting",
    "Prioritization",
    "Time Management",
    "Analytical Thinking",
    "Resource Allocation",
    "Risk Assessment",
    "Systematic Approach",
    "Decision Analysis",
    "Contingency Planning",
    "Evaluation",
  ],
};

export const SKILL_COLORS: Record<SkillName, string> = {
  Listening: "hsl(210, 70%, 55%)",
  Speaking: "hsl(150, 60%, 45%)",
  Leadership: "hsl(25, 85%, 55%)",
  Teamwork: "hsl(270, 60%, 55%)",
  Creativity: "hsl(330, 70%, 55%)",
  Adapting: "hsl(180, 55%, 45%)",
  "Planning & Problem-Solving": "hsl(75, 55%, 45%)",
};
